#
# Exception
#

class LogicError(Exception):
    pass

